// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public interface AgentStrategy {
	/**
	 * 
	 * @param options 
	 * @return 
	 */
	public Action select(Action[] options);
}
