// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class City extends Building {
	/**
	 * 
	 */
	public int getVPValue() {
		// I’m making City worth 2 victory points (standard Catan rule).
		return 2;
	}
}