// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

import java.util.Random;

/************************************************************/
/**
 * 
 */
public class Dice {
	private final Random rng = new Random();

	/**
	 * 
	 */
	public int roll() {
		// I’m simulating 2d6 (two six-sided dice), so the result is 2–12.
		int d1 = rng.nextInt(6) + 1;
		int d2 = rng.nextInt(6) + 1;
		return d1 + d2;
	}
}