// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class GameState {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private ResourceBank bank;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int currentRoll;
	/**
	 * 
	 */
	public ResourceBank resourcebank;

	/**
	 * 
	 */
	public Board getBoard() {
		// I’m returning whichever board reference is set.
		return this.board;
	}

	/**
	 * 
	 */
	public ResourceBank getBank() {
		// I’m syncing the two fields so either name works safely.
		if (this.bank == null) this.bank = this.resourcebank;
		if (this.resourcebank == null) this.resourcebank = this.bank;
		return (this.bank != null) ? this.bank : this.resourcebank;
	}

	// Optional (but useful) helpers for the simulator:
	public void setBoard(Board b) {
		// I’m storing the board in game state so actions/rules can access it.
		this.board = b;
	}

	public void setBank(ResourceBank b) {
		// I’m storing the bank in game state so cost/resource logic can access it.
		this.bank = b;
		this.resourcebank = b;
	}

	public Player[] getPlayers() {
		// I’m exposing players so rule checks and logging can access them.
		return this.players;
	}

	public void setPlayers(Player[] players) {
		this.players = players;
	}

	public int getCurrentRoll() {
		return currentRoll;
	}

	public void setCurrentRoll(int roll) {
		this.currentRoll = roll;
	}
}
