// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private Edge[] incidentEdges;
	/**
	 * 
	 */
	private Tile[] adjacentTiles;
	/**
	 * 
	 */
	public Building building_public;

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
		// I’m treating a node as occupied if it has a building on it.
		// I’m checking both fields because the generator produced a duplicate version.
		return (this.building != null) || (this.building_public != null);
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		// I’m returning the owner of the building on this node (if any).
		Building b = (this.building != null) ? this.building : this.building_public;
		if (b == null) return null;
		return b.getOwner();
	}

	// Optional helpers (useful for settlement/city placement)
	public void setBuilding(Building b) {
		this.building = b;
		this.building_public = b;
	}

	public Building getBuilding() {
		return (this.building != null) ? this.building : this.building_public;
	}

	public int getId() {
		return id;
	}
}