// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class NodeSpec {
	/**
	 * 
	 */
	public int[] adjacentTileIds;
	/**
	 * 
	 */
	public int[] adjacentNodeIds;
	/**
	 * 
	 */
	public TileSpec[] tilespec;

	/**
	 * 
	 * @param adjacentTileIds 
	 * @param adjacentNodeIds 
	 */
	public NodeSpec(int[] adjacentTileIds, int[] adjacentNodeIds) {
		// I’m using this as the real constructor so adjacency ids are set on creation.
		this.adjacentTileIds = (adjacentTileIds != null) ? adjacentTileIds : new int[0];
		this.adjacentNodeIds = (adjacentNodeIds != null) ? adjacentNodeIds : new int[0];

		// I’m initializing this to an empty array until the board layout loader fills it.
		this.tilespec = new TileSpec[0];
	}

	/**
	 * 
	 * @return 
	 */
	public int[] getAdjacentTileIds() {
		// I’m returning the tile adjacency list (never null).
		return (this.adjacentTileIds != null) ? this.adjacentTileIds : new int[0];
	}

	/**
	 * 
	 * @return 
	 */
	public int[] getAdjacentNodeIds() {
		// I’m returning the node adjacency list (never null).
		return (this.adjacentNodeIds != null) ? this.adjacentNodeIds : new int[0];
	}
}