// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class PassAction implements Action {
	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public boolean isExecutable(GameState state, Player p) {
		// I’m allowing pass at any time.
		return true;
	}

	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public void execute(GameState state, Player p) {
		// I’m doing nothing on purpose for a pass.
	}

	/**
	 * 
	 */
	public String describe() {
		// I’m returning a simple description for logging.
		return "Pass";
	}
}