// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

import java.util.Random;

/************************************************************/
/**
 * 
 */
public class RandomStrategy implements AgentStrategy {
	/**
	 * 
	 */
	private Random rng;
	/**
	 * 
	 */
	public Random random;

	/**
	 * 
	 * @param options 
	 * @return 
	 */
	public Action select(Action[] options) {
		// I’m returning null if there are no actions to choose from.
		if (options == null || options.length == 0) return null;

		// I’m initializing my RNG if it wasn’t set yet.
		if (this.rng == null) this.rng = new Random();

		// I’m keeping the public field in sync (since the generator created it).
		this.random = this.rng;

		// I’m choosing a random action from the available options.
		int idx = this.rng.nextInt(options.length);
		return options[idx];
	}
}