// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public enum ResourceType {
	BRICK,
	LUMBER,
	WOOL,
	GRAIN,
	ORE
}