// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class ResourceInventory {
	/**
	 * 
	 */
	private int[] counts;
	/**
	 * 
	 */
	public ResourceType[] resourcetype;

	public ResourceInventory() {
		// I’m initializing counts based on how many resource types exist.
		// I’m assuming ResourceType is an enum.
		this.counts = new int[ResourceType.values().length];
	}

	private int idx(ResourceType type) {
		// I’m mapping a resource type to an index using enum ordinal.
		return type.ordinal();
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void add(ResourceType type, int amount) {
		// I’m ignoring invalid adds.
		if (type == null || amount <= 0) return;
		if (counts == null) counts = new int[ResourceType.values().length];

		counts[idx(type)] += amount;
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void remove(ResourceType type, int amount) {
		// I’m ignoring invalid removes.
		if (type == null || amount <= 0) return;
		if (counts == null) counts = new int[ResourceType.values().length];

		int i = idx(type);
		counts[i] -= amount;
		if (counts[i] < 0) counts[i] = 0; // I’m clamping at 0 to avoid negative counts.
	}

	/**
	 * 
	 */
	public int size() {
		// I’m returning total number of resource cards in this inventory.
		if (counts == null) return 0;
		int sum = 0;
		for (int c : counts) sum += c;
		return sum;
	}

	/**
	 * 
	 * @param cost 
	 */
	public boolean contains(Cost cost) {
		// I’m returning true if I have enough resources to cover the cost.
		if (cost == null) return true;
		if (counts == null) counts = new int[ResourceType.values().length];

		return counts[idx(ResourceType.BRICK)] >= cost.getBrick()
			&& counts[idx(ResourceType.LUMBER)] >= cost.getLumber()
			&& counts[idx(ResourceType.WOOL)] >= cost.getWool()
			&& counts[idx(ResourceType.GRAIN)] >= cost.getGrain()
			&& counts[idx(ResourceType.ORE)] >= cost.getOre();
	}

	// Optional helper so other classes can read counts:
	public int get(ResourceType type) {
		if (type == null) return 0;
		if (counts == null) counts = new int[ResourceType.values().length];
		return counts[idx(type)];
	}
}
