// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Edge location;

	public Road() {
		// I’m keeping a default constructor so I can create roads easily during actions.
	}

	public Road(Player owner, Edge location) {
		// I’m setting owner and location when creating a road.
		this.owner = owner;
		this.location = location;
	}

	public Player getOwner() {
		// I’m exposing the owner so rules and scoring can check ownership.
		return owner;
	}

	public Edge getLocation() {
		return location;
	}

	public void setOwner(Player owner) {
		this.owner = owner;
	}

	public void setLocation(Edge location) {
		this.location = location;
	}
}