// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class RuleEngine {
	/**
	 * 
	 */
	private Board board;

	/**
	 * 
	 * @param p 
	 * @param e 
	 */
	public boolean canBuildRoad(Player p, Edge e) {
		// I’m enforcing basic validity rules:
		// - player and edge must exist
		// - edge must be unoccupied
		// - player must have a road piece
		// - player must be able to afford the road cost
		if (p == null || e == null) return false;
		if (e.isOccupied()) return false;

		PiecePool pool = p.getPieces();
		if (pool != null && !pool.hasRoad()) return false;

		ResourceInventory hand = p.getHand();
		if (hand != null && !hand.contains(Cost.roadCost())) return false;

		return true;
	}

	/**
	 * 
	 * @param p 
	 * @param n 
	 */
	public boolean canBuildSettlement(Player p, Node n) {
		// I’m enforcing basic validity rules:
		// - node must exist and be unoccupied
		// - player must have a settlement piece
		// - player must be able to afford settlement cost
		if (p == null || n == null) return false;
		if (n.isOccupied()) return false;

		PiecePool pool = p.getPieces();
		if (pool != null && !pool.hasSettlement()) return false;

		ResourceInventory hand = p.getHand();
		if (hand != null && !hand.contains(Cost.settlementCost())) return false;

		// Later I’ll add:
		// - distance rule (no adjacent settlements)
		// - must be connected to own road (except initial placement)
		return true;
	}

	/**
	 * 
	 * @param p 
	 * @param n 
	 */
	public boolean canUpgradeToCity(Player p, Node n) {
		// I’m enforcing basic validity rules:
		// - node must exist and be occupied by the player’s building
		// - player must have a city piece
		// - player must be able to afford city cost
		if (p == null || n == null) return false;
		if (!n.isOccupied()) return false;

		Building b = n.getBuilding();
		if (b == null) return false;
		if (b.getOwner() != p) return false;

		// If it’s already a City, no upgrade needed.
		if (b instanceof City) return false;

		PiecePool pool = p.getPieces();
		if (pool != null && !pool.hasCity()) return false;

		ResourceInventory hand = p.getHand();
		if (hand != null && !hand.contains(Cost.cityCost())) return false;

		return true;
	}
}