// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class Settlement extends Building {
	/**
	 * 
	 */
	public int getVPValue() {
		// I’m making a Settlement worth 1 victory point (standard Catan rule).
		return 1;
	}
}