// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public enum TerrainType {
	HILLS,
	FOREST,
	PASTURE,
	FIELDS,
	MOUNTAINS,
	DESERT
}