// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class UpgradeToCityAction implements Action {
	/**
	 * 
	 */
	public Node target;

	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public boolean isExecutable(GameState state, Player p) {
		// I’m doing the basic legality checks here.
		if (state == null || p == null || target == null) return false;
		if (!target.isOccupied()) return false;

		Building b = target.getBuilding();
		if (b == null) return false;
		if (b.getOwner() != p) return false;
		if (b instanceof City) return false;

		// I’m checking the player can afford the city cost and has a city piece.
		if (!p.canAfford(Cost.cityCost())) return false;

		PiecePool pool = p.getPieces();
		if (pool != null && !pool.hasCity()) return false;

		return true;
	}

	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public void execute(GameState state, Player p) {
		// I’m only executing if it’s allowed.
		if (!isExecutable(state, p)) return;

		// I’m paying the cost.
		p.pay(Cost.cityCost());

		// I’m updating the piece pool: take a city and return a settlement.
		PiecePool pool = p.getPieces();
		if (pool != null) {
			pool.takeCity();
			pool.returnSettlement();
		}

		// I’m replacing the settlement with a city on the target node.
		City city = new City();
		target.setBuilding(city);

		// I’m updating victory points (+1 net, since settlement 1 -> city 2).
		p.addVictoryPoints(1);
	}

	/**
	 * 
	 */
	public String describe() {
		// I’m returning a clear action label for logging.
		return "UpgradeToCity";
	}
}
