// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class ActionGenerator {
	/**
	 * 
	 */
	private RuleEngine rules;

	/**
	 * 
	 * @param state 
	 * @param p 
	 * @param mustBuild 
	 */
	public Action[] getExecutableActions(GameState state, Player p, boolean mustBuild) {
		// I’m returning an empty list for now so everything compiles.
		// Later, I’ll generate candidate actions and filter using rules + mustBuild.
		return new Action[0];
	}
}