// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class ActionLogger {
	/**
	 * 
	 * @param round 
	 * @param playerId 
	 * @param description 
	 */
	public void logAction(int round, int playerId, String description) {
		// I’m printing exactly in the required format: [RoundNumber] / [PlayerID]: [Action]
		System.out.println(round + " / " + playerId + ": " + description);
	}

	/**
	 * 
	 * @param round 
	 * @param players
	 */
	public void logEndOfRound(int round, Player[] players) {
		// I’m printing end-of-round victory points for each player.
		// I’m keeping the format readable and consistent.
		if (players == null) return;

		for (int i = 0; i < players.length; i++) {
			Player p = players[i];
			if (p == null) continue;

			// I’m assuming Player has getVictoryPoints().
			// If your Player uses a different name, tell me and I’ll adjust it.
			int vp = 0;
			try {
				vp = p.getVictoryPoints();
			} catch (Exception e) {
				// I’m leaving vp as 0 if the method doesn’t exist yet.
			}

			System.out.println(round + " / " + i + ": VP=" + vp);
		}
	}
}