// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public interface Action {
	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public boolean isExecutable(GameState state, Player p);

	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public void execute(GameState state, Player p);

	/**
	 * 
	 */
	public String describe();
}
