// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class BoardLayout {
	/**
	 * 
	 */
	private TileSpec[] tileDefinitions;
	/**
	 * 
	 */
	private NodeSpec[] nodeDefinitions;
	/**
	 * 
	 */
	private EdgeSpec[] edgeDefinitions;
	/**
	 * 
	 */
	public NodeSpec[] nodespec;
	/**
	 * 
	 */
	public TileSpec[] tilespec;
	/**
	 * 
	 */
	public EdgeSpec[] edgespec;

	/**
	 * 
	 * @return 
	 * @param tileId 
	 */
	public TileSpec getTileSpec(int tileId) {
		// I’m returning the TileSpec by index from whichever array is populated.
		TileSpec[] src = (tileDefinitions != null) ? tileDefinitions : tilespec;
		if (src == null) return null;
		if (tileId < 0 || tileId >= src.length) return null;
		return src[tileId];
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public NodeSpec getNodeSpec(int nodeId) {
		// I’m returning the NodeSpec by index from whichever array is populated.
		NodeSpec[] src = (nodeDefinitions != null) ? nodeDefinitions : nodespec;
		if (src == null) return null;
		if (nodeId < 0 || nodeId >= src.length) return null;
		return src[nodeId];
	}

	/**
	 * 
	 * @param edgeIndex 
	 * @return 
	 */
	public EdgeSpec getEdgeSpec(int edgeIndex) {
		// I’m returning the EdgeSpec by index from whichever array is populated.
		EdgeSpec[] src = (edgeDefinitions != null) ? edgeDefinitions : edgespec;
		if (src == null) return null;
		if (edgeIndex < 0 || edgeIndex >= src.length) return null;
		return src[edgeIndex];
	}
}