// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class Building {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Node location;

	/**
	 * 
	 */
	public int getVPValue() {
		// I’m returning a default of 1 VP for a basic building.
		// Later, I’ll override this in subclasses (e.g., City = 2 VP).
		return 1;
	}

	// Optional (but useful): getters so other classes can access these fields safely.
	public Player getOwner() {
		// I’m exposing the owner so Node.getOwner() and scoring can work.
		return this.owner;
	}

	public Node getLocation() {
		return this.location;
	}
}