// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class BuildRoadAction implements Action {
	/**
	 * 
	 */
	public Edge target;

	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public boolean isExecutable(GameState state, Player p) {
		// I’m doing a safe minimal check so the simulator can run:
		// - must have a target edge
		// - edge must not already be occupied
		if (target == null) return false;
		if (p == null || state == null) return false;

		return !target.isOccupied();
	}

	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public void execute(GameState state, Player p) {
		// I’m only executing if it’s allowed.
		if (!isExecutable(state, p)) return;

	}

	/**
	 * 
	 */
	public String describe() {
		// I’m returning a simple string that can be logged in the required format.
		// Later I can include edge endpoint ids, etc.
		return "BuildRoad";
	}
}

