// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class BuildSettlementAction implements Action {
	/**
	 * 
	 */
	public Node target;

	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public boolean isExecutable(GameState state, Player p) {
		// I’m doing a safe minimal check so the simulator can run:
		// - must have a target node
		// - node must not already be occupied
		// Proper Catan rules (distance rule, adjacency to own road, resource cost)
		// will be enforced later via RuleEngine.
		if (target == null) return false;
		if (p == null || state == null) return false;

		return !target.isOccupied();
	}

	/**
	 * 
	 * @param state 
	 * @param p 
	 */
	public void execute(GameState state, Player p) {
		// I’m only executing if it’s allowed.
		if (!isExecutable(state, p)) return;

		// I’m leaving this as a placeholder because I need your Building/Node API.
		// Later I will:
		// - create a Settlement (or Building with VP=1) owned by p
		// - place it on the target node
		// - update player victory points/resources if your model tracks it
	}

	/**
	 * 
	 */
	public String describe() {
		// I’m returning a simple string for logging in the required format.
		return "BuildSettlement";
	}
}
