// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class ConfigLoader {
	/**
	 * 
	 * @param path 
	 * @return 
	 */
	public SimulationConfig load(String path) {
		// I’m returning a default config so the generated code compiles and the simulator can start.
		// Later I’ll read the file at 'path' and populate all required fields (e.g., turns).
		return new SimulationConfig();
	}
}