// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class Cost {
	/**
	 * 
	 */
	private int brick;
	/**
	 * 
	 */
	private int lumber;
	/**
	 * 
	 */
	private int wool;
	/**
	 * 
	 */
	private int grain;
	/**
	 * 
	 */
	private int ore;
	/**
	 * 
	 */
	public ResourceType[] resourcetype;

	/**
	 * 
	 */
	public static Cost roadCost() {
		// I’m using standard Catan costs:
		// Road = 1 brick + 1 lumber
		Cost c = new Cost();
		c.brick = 1;
		c.lumber = 1;
		return c;
	}

	/**
	 * 
	 */
	public static Cost settlementCost() {
		// I’m using standard Catan costs:
		// Settlement = 1 brick + 1 lumber + 1 wool + 1 grain
		Cost c = new Cost();
		c.brick = 1;
		c.lumber = 1;
		c.wool = 1;
		c.grain = 1;
		return c;
	}

	/**
	 * 
	 */
	public static Cost cityCost() {
		// I’m using standard Catan costs:
		// City = 2 grain + 3 ore
		Cost c = new Cost();
		c.grain = 2;
		c.ore = 3;
		return c;
	}

	// Optional helper getters (useful later for RuleEngine checks)
	public int getBrick() { return brick; }
	public int getLumber() { return lumber; }
	public int getWool() { return wool; }
	public int getGrain() { return grain; }
	public int getOre() { return ore; }
}