// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class EdgeSpec {
	/**
	 * 
	 */
	public int nodeAId;
	/**
	 * 
	 */
	public int nodeBId;
	/**
	 * 
	 */
	public NodeSpec[] nodespec;

	/**
	 * 
	 * @param nodeAId 
	 * @param nodeBId 
	 */
	public EdgeSpec(int nodeAId, int nodeBId) {
		// I’m using this as the real constructor so the ids are set when the object is created.
		this.nodeAId = nodeAId;
		this.nodeBId = nodeBId;

		// I’m initializing to an empty array so nothing crashes until I load real NodeSpecs.
		this.nodespec = new NodeSpec[0];
	}

	/**
	 * 
	 * @return 
	 */
	public int getNodeAId() {
		return this.nodeAId;
	}

	/**
	 * 
	 * @return 
	 */
	public int getNodeBId() {
		return this.nodeBId;
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public boolean connects(int nodeId) {
		// I’m checking whether the given node id matches either endpoint of the edge.
		return nodeId == this.nodeAId || nodeId == this.nodeBId;
	}
}