// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private Node a;
	/**
	 * 
	 */
	private Node b;
	/**
	 * 
	 */
	private Road road;
	/**
	 * 
	 */
	public Node[] node;
	/**
	 * 
	 */
	public Road road_public;

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
		// I’m treating an edge as occupied if it has a road on it.
		// I’m checking both fields because the generator created a duplicate version.
		return (this.road != null) || (this.road_public != null);
	}

	// Optional helpers (useful for BuildRoadAction later)
	public void setRoad(Road r) {
		// I’m setting both so whichever field the rest of my code uses stays consistent.
		this.road = r;
		this.road_public = r;
	}

	public Road getRoad() {
		return (this.road != null) ? this.road : this.road_public;
	}

	public Node getA() { return a; }
	public Node getB() { return b; }
}