// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class PiecePool {
	/**
	 * 
	 */
	private int roadsRemaining;
	/**
	 * 
	 */
	private int settlementsRemaining;
	/**
	 * 
	 */
	private int citiesRemaining;

	/**
	 * 
	 */
	public boolean hasRoad() {
		// I’m checking if I still have at least one road piece left.
		return roadsRemaining > 0;
	}

	/**
	 * 
	 */
	public void takeRoad() {
		// I’m consuming a road piece if one is available.
		if (roadsRemaining > 0) roadsRemaining--;
	}

	/**
	 * 
	 */
	public boolean hasSettlement() {
		// I’m checking if I still have at least one settlement piece left.
		return settlementsRemaining > 0;
	}

	/**
	 * 
	 */
	public void takeSettlement() {
		// I’m consuming a settlement piece if one is available.
		if (settlementsRemaining > 0) settlementsRemaining--;
	}

	/**
	 * 
	 */
	public boolean hasCity() {
		// I’m checking if I still have at least one city piece left.
		return citiesRemaining > 0;
	}

	/**
	 * 
	 */
	public void takeCity() {
		// I’m consuming a city piece if one is available.
		if (citiesRemaining > 0) citiesRemaining--;
	}

	/**
	 * 
	 */
	public void returnSettlement() {
		// I’m returning a settlement piece back into the pool.
		settlementsRemaining++;
	}

	// Optional helpers so setup/config can initialize piece counts:
	public void setRoadsRemaining(int n) { this.roadsRemaining = n; }
	public void setSettlementsRemaining(int n) { this.settlementsRemaining = n; }
	public void setCitiesRemaining(int n) { this.citiesRemaining = n; }

	public int getRoadsRemaining() { return roadsRemaining; }
	public int getSettlementsRemaining() { return settlementsRemaining; }
	public int getCitiesRemaining() { return citiesRemaining; }
}
