// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceInventory hand;
	/**
	 * 
	 */
	private PiecePool pieces;
	/**
	 * 
	 */
	private AgentStrategy strategy;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	public Building[] building;
	/**
	 * 
	 */
	public Road[] road;
	/**
	 * 
	 */
	public ResourceInventory resourceinventory;
	/**
	 * 
	 */
	public PiecePool piecepool;
	/**
	 * 
	 */
	public AgentStrategy agentstrategy;

	/**
	 * 
	 * @return 
	 */
	public int getId() {
		// I’m returning the player id.
		return this.id;
	}

	/**
	 * 
	 * @return 
	 */
	public int getVP() {
		// I’m returning the current victory points.
		return this.victoryPoints;
	}

	// Optional helper so other parts of my code can use a clearer name.
	public int getVictoryPoints() {
		// I’m keeping this consistent with getVP().
		return getVP();
	}

	/**
	 * 
	 * @return 
	 */
	public int handSize() {
		// I’m returning 0 if the hand isn’t initialized yet.
		if (this.hand == null && this.resourceinventory != null) {
			this.hand = this.resourceinventory;
		}
		if (this.hand == null) return 0;

		// I don’t know your ResourceInventory API yet, so I’m doing a safe fallback.
		// If you have a size/total method later, plug it in here.
		try {
			return this.hand.size();
		} catch (Exception e) {
			return 0;
		}
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean canAfford(Cost cost) {
		// I’m defaulting to true if cost is null.
		if (cost == null) return true;

		// I’m syncing the hand fields first.
		if (this.hand == null && this.resourceinventory != null) {
			this.hand = this.resourceinventory;
		}
		if (this.resourceinventory == null) {
			this.resourceinventory = this.hand;
		}

		// I can’t do a real affordability check until I know ResourceInventory’s API.
		// For now, I’m returning true so the simulator can run (RuleEngine will enforce later).
		return true;
	}

	/**
	 * 
	 * @param cost 
	 */
	public void pay(Cost cost) {
		// I’m doing nothing if cost is null.
		if (cost == null) return;

		// I’m syncing the hand fields first.
		if (this.hand == null && this.resourceinventory != null) {
			this.hand = this.resourceinventory;
		}
		if (this.resourceinventory == null) {
			this.resourceinventory = this.hand;
		}

		// I can’t subtract resources until I know ResourceInventory’s API.
		// For now, I’m leaving this as a no-op so compilation succeeds.
	}

	/**
	 * 
	 * @param bundle 
	 */
	public void addResources(ResourceInventory bundle) {
		// I’m doing nothing if bundle is null.
		if (bundle == null) return;

		// I’m syncing the hand fields first.
		if (this.hand == null && this.resourceinventory != null) {
			this.hand = this.resourceinventory;
		}
		if (this.resourceinventory == null) {
			this.resourceinventory = this.hand;
		}

		// I can’t add resources until I know ResourceInventory’s API.
		// For now, I’m leaving this as a no-op so compilation succeeds.
	}

	/**
	 * 
	 * @param options 
	 * @return 
	 */
	public Action chooseAction(Action[] options) {
		// I’m returning null if there are no options.
		if (options == null || options.length == 0) return null;

		// I’m syncing the strategy fields.
		if (this.strategy == null && this.agentstrategy != null) {
			this.strategy = this.agentstrategy;
		}
		if (this.agentstrategy == null) {
			this.agentstrategy = this.strategy;
		}

		// If I have a strategy, I’ll let it pick.
		if (this.strategy != null) {
			Action chosen = this.strategy.select(options);
			if (chosen != null) return chosen;
		}

		// Otherwise, I’m picking the first action as a simple default.
		return options[0];
	}

	// Optional setters to help SetupManager/config initialize players cleanly:
	public void setId(int id) { this.id = id; }
	public void setVictoryPoints(int vp) { this.victoryPoints = vp; }
	public void addVictoryPoints(int delta) { this.victoryPoints += delta; }

	public ResourceInventory getHand() {
		if (this.hand == null) this.hand = this.resourceinventory;
		return this.hand;
	}

	public PiecePool getPieces() {
		if (this.pieces == null) this.pieces = this.piecepool;
		return this.pieces;
	}
}
