// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class ResourceBank {
	/**
	 * 
	 */
	private ResourceInventory supply;
	/**
	 * 
	 */
	public ResourceInventory resourceinventory;

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public boolean canPay(ResourceType type, int amount) {
		// I’m returning false for invalid requests.
		if (type == null) return false;
		if (amount <= 0) return true;

		// I’m syncing the two fields so either one can be used.
		if (this.supply == null) this.supply = this.resourceinventory;
		if (this.resourceinventory == null) this.resourceinventory = this.supply;

		// I can’t do a real check until I know ResourceInventory’s API.
		// For now, I’m assuming the bank can pay (simulator won’t crash).
		return true;
	}

	/**
	 * 
	 * @param player 
	 * @param type 
	 * @param amount 
	 */
	public void payTo(Player player, ResourceType type, int amount) {
		// I’m not doing anything if the request is invalid.
		if (player == null || type == null || amount <= 0) return;

		// I’m only paying if the bank can pay.
		if (!canPay(type, amount)) return;

		// I can’t actually transfer resources until ResourceInventory is implemented.
		// Later I will:
		// 1) subtract (type, amount) from bank supply
		// 2) add (type, amount) to player hand
	}
}