// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class SetupManager {
	/**
	 * 
	 * @param players 
	 * @param board 
	 * @param rules 
	 */
	public void placeInitialPieces(Player[] players, Board board, RuleEngine rules) {
		// I’m doing a safe setup so the simulator can run without null crashes.
		if (players == null || players.length == 0) return;

		for (int i = 0; i < players.length; i++) {
			Player p = players[i];
			if (p == null) continue;

			// I’m ensuring each player has a hand and piece pool.
			if (p.getHand() == null) {
				// Player.getHand() already syncs fields; I’m forcing initialization here.
				p.addResources(new ResourceInventory());
			}
			if (p.getPieces() == null) {
				PiecePool pool = new PiecePool();

				// I’m setting standard Catan piece counts.
				// Roads: 15, Settlements: 5, Cities: 4
				pool.setRoadsRemaining(15);
				pool.setSettlementsRemaining(5);
				pool.setCitiesRemaining(4);

				p.piecepool = pool; // I’m setting the public field since the generator created it.
			}

			// Later I will actually place the initial settlement(s) and road(s) on the board:
			// - choose valid Node targets
			// - enforce distance rule
			// - place Settlement on node
			// - place Road on an adjacent edge
		}
	}
}