// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class SimulationConfig {
	/**
	 * 
	 */
	private int turns;

	public SimulationConfig() {
		// I’m setting a safe default so the simulator can run even if no config file is loaded.
		this.turns = 1;
	}

	/**
	 * 
	 * @param Parameter1 
	 */
	public int getTurns(int Parameter1) {
		// I’m ignoring Parameter1 because this method is supposed to return the configured turns.
		// I’m keeping the parameter only because Papyrus generated it that way.
		return this.turns;
	}

	// Optional (but needed in practice): setter with validation
	public void setTurns(int turns) {
		// I’m enforcing the assignment constraint: turns must be in [1, 8192].
		if (turns < 1) turns = 1;
		if (turns > 8192) turns = 8192;
		this.turns = turns;
	}
}