// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class TileSpec {
	/**
	 * 
	 */
	private TerrainType terrain;
	/**
	 * 
	 */
	private int token;

	/**
	 * 
	 * @param terrain 
	 * @param token 
	 */
	public TileSpec(TerrainType terrain, int token) {
		// I’m using this as the real constructor so the tile spec is set when created.
		this.terrain = terrain;
		this.token = token;
	}

	/**
	 * 
	 * @return 
	 */
	public TerrainType getTerrain() {
		// I’m returning the terrain type for this tile.
		return this.terrain;
	}

	/**
	 * 
	 * @param Parameter1 
	 */
	public int getToken(int Parameter1) {
		// I’m ignoring Parameter1 because this method should return the token number.
		return this.token;
	}
}