// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package asisgnment01_uml;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private TerrainType terrain;
	/**
	 * 
	 */
	private int token;
	/**
	 * 
	 */
	private Node[] cornerNodes;
	/**
	 * 
	 */
	public Node[] cornerNodes_public;
	/**
	 * 
	 */
	public TerrainType terraintype;

	/**
	 * 
	 * @param roll 
	 * @return 
	 */
	public boolean producesOn(int roll) {
		// I’m producing if the roll matches the tile’s token number.
		// Desert typically has no token / produces nothing; this check still safely returns false if token isn’t set.
		return this.token == roll;
	}

	/**
	 * 
	 * @param Parameter1 
	 */
	public ResourceType getProducedResource(ResourceType Parameter1) {
		// I’m ignoring Parameter1 because this method should return the resource produced by this tile.
		// I’m mapping terrain to a resource type using standard Catan rules.
		TerrainType t = (this.terrain != null) ? this.terrain : this.terraintype;
		if (t == null) return null;

		switch (t) {
			case HILLS: return ResourceType.BRICK;
			case FOREST: return ResourceType.LUMBER;
			case PASTURE: return ResourceType.WOOL;
			case FIELDS: return ResourceType.GRAIN;
			case MOUNTAINS: return ResourceType.ORE;
			case DESERT: default: return null;
		}
	}

	// Optional helpers (useful later)
	public int getId() { return id; }
	public int getToken() { return token; }

	public Node[] getCornerNodes() {
		// I’m returning whichever corner node array exists.
		if (this.cornerNodes == null) this.cornerNodes = this.cornerNodes_public;
		if (this.cornerNodes_public == null) this.cornerNodes_public = this.cornerNodes;
		return (this.cornerNodes != null) ? this.cornerNodes : this.cornerNodes_public;
	}
}
